### ISSUE TITLE
Proposal for a Protocluster-Track Match

### ISSUE THREAD

**Issue by ruse-traveler** [eic/EDM4eic#107]
**Is your feature request related to a problem? Please describe.**

It was proposed in discussion to [EICrecon#1699](https://github.com/eic/EICrecon/pull/1699) to update the `TrackClusterMergeSplitter` algorithm so that it consumes clusters, and then outputs protoclusters so that they can be reconstructed by `ClusterRecoCoG` and consumed by downstream PF algorithms. Since connections between the merged/split clusters and their antecedent tracks are crucial to these downstream algorithms, there will need to be changes to the data model to propagate this information.

**Describe the solution you'd like**

Part of the proposal by @veprbl in [EICrecon#1699](https://github.com/eic/EICrecon/pull/1699) was to add a `ProtoClusterTrackMatch` type (parallel to `edm4eic::ClusterTrackMatch`). This type would look something like this:

```
  edm4eic::TrackProtoClusterMatch:
    Description: "Match between a ProtoCluster and a Track"
    Author: "D. Kalinkin, D. Anderson"
    Members:
      - float weight  // weight of this association
    OneToOneRelations:
      - edm4eic::ProtoCluster protocluster  // reference to the protocluster
      - edm4eic::Track        track         // reference to the track
```

The type's introduction to the data model would be followed by a PR to EICrecon to add a "promotion" algorithm that would copy the protocluster-track matches to the relevant cluster-track matches after their CoG reconstruction.

**Describe alternatives you've considered**

An alternative could be to instead deprecate `edm4eic::ProtoCluster` and use the `edm4eic::Cluster` in all clustering/reclustering algorithms since the latter is a superset of the former. While this certainly should be considered at some point, this would be less preferable in the near term as it would necessitate updating several algorithms in EICrecon.

**Additional context**
