### ISSUE TITLE
Proposal for Waveform and Raw HGCROC Hit

### ISSUE THREAD

**Issue by ruse-traveler** [eic/EDM4eic#89]
![PXL_20240725_235606610](https://github.com/user-attachments/assets/897cc527-f1e5-47db-95d6-ee5451902eac)

One of the items discussed during the [July 2024 ePIC Collaboration Meeting](https://indico.bnl.gov/event/20727/sessions/7437/#20240725) was the steps needed to better simulate the HGCROC. One thing identified was the need to make sure we have the data types necessary to capture both the waveform produced by a SiPM as well as the output of the HGCROC.

**Describe the solution you'd like**

 For the waveform, we could make use of `edm4hep::RawTimeSeries` (from [here](https://github.com/key4hep/EDM4hep/blob/a173bdec749abf5447810b25286a64456914faa6/edm4hep.yaml#L510)).:

```
  edm4hep::RawTimeSeries:
    Description: "Raw data of a detector readout"
    Author: "EDM4hep authors"
    Members:
       - uint64_t cellID  // detector specific cell id
       - int32_t quality               // quality flag for the hit
       - float time [ns]               // time of the hit
       - float charge [fC]             // integrated charge of the hit
       - float interval [ns]           // interval of each sampling
    VectorMembers:
       - int32_t adcCounts          // raw data (32-bit) word at i
```

But for the HGCROC output, we would need to extend what's already in `edm4hep::RawCalorimeterHit`. For example:

```
edm4eic::RawHGCROCHit:
  Description: "Raw hit from an HGCROC"
  Author: "H. G. Croc"
  Members:
    - uint64_t cellID // detector specific (geometrical) cell id
    - int32_t timeOfArrival // ToA value [adc counts]
    - int32_t timeOverThreshold // ToT value [adc counts]
    - int32_t amplitude // amplitude of hit [adc counts]
    - int32_t timeSamp // time stamp for the hit
```

**Describe alternatives you've considered**

One alternate approach could be to save only one of the values from the HGCROC (e.g. amplitude) in `edm4hep::RawCalorimeterHit`

**Comment by veprbl** [comment]
ToA is already part of the edm4hep::RawCalorimeterHit. ToT we could add in our own extension in edm4eic:: namespace, or even submit that upstream. A different question is how to store waveforms between the simulation-type algorithms.

**Comment by ruse-traveler** [comment]
> ToA is already part of the edm4hep::RawCalorimeterHit

Is it? I'm seeing an amplitude field, but not a ToA field...

```
  #-------------  RawCalorimeterHit
  edm4hep::RawCalorimeterHit:
    Description: "Raw calorimeter hit"
    Author: "EDM4hep authors"
    Members:
      - uint64_t cellID   // detector specific (geometrical) cell id
      - int32_t amplitude               // amplitude of the hit in ADC counts
      - int32_t timeStamp               // time stamp for the hit
```

Either way, I'd also be okay with adding the ToT (and ToA if needed) to our extension or upstream!
